#!/bin/bash

### SET COLOUR CODE ###
RED='\e[0;31m'      #Red
GREEN='\e[0;32m'    #Green
YELLOW='\e[0;33m'   #Yellow
BLUE='\e[0;34m'     #Blue
PURPLE='\e[0;35m'   #Purple
CYAN='\e[0;36m'     #Cyan
GRAY='\e[0;37m'     #Gray
BRED='\e[1;31m'     #Bold red
BGREEN='\e[1;32m'   #Bold green
BYELLOW='\e[1;33m'  #Bold yellow
BBLUE='\e[1;34m'    #Bold blue
BPURPLE='\e[1;35m'  #Bold purple
BCYAN='\e[1;36m'    #Bold cyan
BGRAY='\e[1;37m'    #Bold gray
CRESET='\e[0m'		#Reset color

nocolor() {
	
	RED=''
	GREEN=''
	YELLOW=''
	BLUE=''
	PURPLE=''
	CYAN=''
	GRAY=''
	BRED=''
	BGREEN=''
	BYELLOW=''
	BBLUE=''
	BPURPLE=''
	BCYAN=''
	BGRAY=''
	CRESET=''

}
