#!/bin/bash

### SET COLOUR CODE ###
color_red='\e[0;31m'      #Red
color_green='\e[0;32m'    #Green
color_yellow='\e[0;33m'   #Yellow
color_blue='\e[0;34m'     #Blue
color_purple='\e[0;35m'   #Purple
color_cyan='\e[0;36m'     #Cyan
color_gray='\e[0;37m'     #Gray
color_bred='\e[1;31m'     #Bold red
color_bgreen='\e[1;32m'   #Bold green
color_byellow='\e[1;33m'  #Bold yellow
color_bblue='\e[1;34m'    #Bold blue
color_bpurple='\e[1;35m'  #Bold purple
color_bcyan='\e[1;36m'    #Bold cyan
color_bgray='\e[1;37m'    #Bold gray
color_reset='\e[0m' 	  #Reset color

nocolor() {
	
	color_red=''
	color_green=''
	color_yellow=''
	color_blue=''
	color_purple=''
	color_cyan=''
	color_gray=''
	color_bred=''
	color_bgreen=''
	color_byellow=''
	color_bblue=''
	color_bpurple=''
	color_bcyan=''
	color_bgray=''
	color_reset=''

}
