#!/bin/bash

msg() {
	echo -e "${GREEN}==>${CRESET} $1"
}

msginfo() {
	echo -e "${CYAN}==> INFO:${CRESET} $1"
}

msgerr() {
	echo -e "${RED}==> ERROR:${CRESET} $1"
}

msgwarn() {
	echo -e "${YELLOW}==> WARNING:${CRESET} $1"
}

msg2() {
	echo -e "${BLUE}  ->${CRESET} $1"
}

msg3() {
	echo -e "$1"
}

msg4() {
	echo -e "     $1"
}
