." Man page for pkgbuild
."
.TH pkgbuild 8 "" ""
.SH NAME
pkgbuild - package creator

.SH SYNOPSIS
pkgbuild <options>

.SH DESCRIPTION
\fIpkgbuild\fP is a tool to build package from ports. Is will source \fIspkgbuild\fP
to get build information before creating package. Package is created into 
\fI<name>-<version>-<release>.spkg.tar.xz\fP format. To build package, you need
change into port directory before run \fIpkgbuild\fP command.

.SH OPTIONS
.TP
.B "-i, --install"
install package into system
.TP
.B "-u, --upgrade"
upgrade package
.TP
.B "-r, --reinstall"
reinstall package
.TP
.B "-c, --ignore-conflict"
ignore conflict when installing package
.TP
.B "-v, --verbose"
verbose install process
.TP
.B "-f, --force-rebuild"
rebuild package
.TP
.B "-m, --skip-mdsum"
skip md5sum checking
.TP
.B "-g, --genmdsum"
generate md5sum
.TP
.B "-o, --download"
download only source file
.TP
.B "-x, --extract"
extract only source file
.TP
.B "-b, "--build-only"
build and package without downloading and extracting source
.TP
.B "-w, --keep-work"
keep working directory
.TP
.B "-s, --silent"
print install message in simple format
.TP
.B "-h, --help"
show this help message
.TP
.B "--srcdir=<path>"
override directory path for sources
.TP
.B "--pkgdir=<path>"
override directory path for compiled package
.TP
.B "--no-prebuild"
skip prebuild script before build package
.TP
.B "--no-preinstall"
skip preinstall script before install package
.TP
.B "--no-postinstall"
skip postinstall script after install package
.TP
.B "--no-preupgrade"
skip preupgrade script before upgrade package
.TP
.B "--no-postupgrade"
skip postupgrade script after upgrade package
.TP
.B "--no-backup"
skip backup configuration file when upgrading package
.TP
.B "--redownload"
re-download source file

.SH AUTHOR
Emmett1 <emmett1.2miligrams@gmail.com>

.SH SEE ALSO
pkgadd(8), pkgdel(8), revdep(8)
