#!/bin/bash
#
#  scratchpkg
#
#  Copyright (c) 2018 by Emmett1  (emmett1.2miligrams@gmail.com)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

set -e

INDEX_DIR="/var/lib/scratchpkg/index"

RED='\e[0;31m'      #Red
GREEN='\e[0;32m'    #Green
YELLOW='\e[0;33m'   #Yellow
CYAN='\e[0;36m'     #Cyan
CRESET='\e[0m'		#Reset color

msgerr() {
	echo -e "${RED}==> ERROR:${CRESET} $1"
}

if [ ! $1 ]; then
	msgerr "This script requires one arguments."
	exit 1
fi

if [ ! -d $INDEX_DIR/$1 ]; then
	msgerr "Package '$1' not installed."
	exit 1
fi

pushd / >/dev/null
	while IFS=' ' read -r LINE; do
		case "$(file -Lbi "${LINE}")" in
			*application/x-sharedlib* | *application/x-executable* | *application/x-pie-executable*)
			NEEDED_LIB=$(objdump -x "$LINE" | grep NEEDED | awk '{print $2}')
			for i in ${NEEDED_LIB[@]}; do
				if [ "$i" != "ld-linux-x86-64.so.2" ]; then
					libpath=$(ldd "$LINE" | grep -v "not found" | grep -w "$i" | awk '{print $3}')
					if [ "$libpath" ]; then
						FILEPATH=$(readlink -f $(echo $libpath))
						FILENAME=$(echo $FILEPATH | sed -e '1s/^.//')
						PKG_NAME=$(basename $(dirname $(grep -Rx $FILENAME $INDEX_DIR | cut -d ':' -f1)))
						if [ "$PKG_NAME" != $1 ]; then
							if [ ! "$(echo "$deppkg" | grep -w "$PKG_NAME")" ]; then
								deppkg="$deppkg $PKG_NAME "
							fi
						fi
					else
						echo "$LINE (missing shared lib) => $i"
					fi
				fi
			done
		esac
	done < <(tac $INDEX_DIR/$1/.files | grep -E ^"(bin/|lib/|libexec/|sbin/|usr/bin/|usr/lib/|usr/libexec/|usr/sbin/)" | grep -v "/$")
popd >/dev/null

echo $deppkg | tr ' ' '\n'
