#!/bin/sh
#
# script to rebuild base packages in right toolchain order
#

LIST="/tmp/$(basename $0)-list"
touch $LIST

TOOLCHAIN="linux-api-headers glibc-pass1 binutils-pass1 gcc binutils glibc"

#scratch sync || exit 1

for tc in $TOOLCHAIN; do
	if [ ! $(grep -x $tc $LIST) ]; then
		pkgname="$(echo $tc | sed 's/-pass1//')"
		scratch build -f $pkgname || exit 1
		echo $tc >> $LIST
		scratch install -r $pkgname --no-backup || exit 1
	fi
done	

for pkg in $(scratch deplist base | awk '{print $2}'); do
	case $pkg in
		linux-api-headers|musl|gcc|binutils|glibc) continue;;
	esac
	if [ ! $(grep -x $pkg $LIST) ]; then
		scratch build -f $pkg || exit 1
		echo $pkg >> $LIST
		scratch install -r $pkg --no-backup || exit 1
	fi
done

exit 0
