#!/bin/sh
#
#  scratchpkg
#
#  Copyright (c) 2018 by Emmett1  (emmett1.2miligrams@gmail.com)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#
#  script to rebuild base packages in right toolchain order
#

LIST="/tmp/$(basename $0)-list"
touch $LIST

TOOLCHAIN="linux-api-headers glibc-pass1 binutils-pass1 gcc-pass1 glibc binutils gcc"

#scratch sync || exit 1

for tc in $TOOLCHAIN; do
	if [ ! $(grep -x $tc $LIST) ]; then
		pkgname="$(echo $tc | sed 's/-pass1//')"
		scratch build -f $pkgname || exit 1
		echo $tc >> $LIST
		scratch install -r $pkgname || exit 1
	fi
done	

for pkg in $(scratch deplist base | awk '{print $2}'); do
	case $pkg in
		linux-api-headers|musl|gcc|binutils|glibc) continue;;
	esac
	if [ ! $(grep -x $pkg $LIST) ]; then
		scratch build -f $pkg || exit 1
		echo $pkg >> $LIST
		scratch install -r $pkg || exit 1
	fi
done

exit 0
