#!/bin/bash -e

calcdep() {
	
	dep=$(scratch -d $1 | grep -v "port not exist" | awk '{print $3}')
	for i in $dep; do
		deps="$deps $i"
	done
	
}

loop() {
	
	for depends in ${dep[@]}; do
		if [ "$(echo "$checked" | tr ' ' '\n' | grep -x "$depends")" ]; then
			continue
		else
			checked="$checked $depends"
		fi
		#echo $checked
		calcdep $depends
		loop
	done
}

checkpkg() {
	
	for repo in ${PORT_REPO[@]}; do
		if [ -f $repo/$pkgname/spkgbuild ]; then
			PORT_EXIST=yes
			break
		fi
	done
	[ "$PORT_EXIST" ] || (echo "Port $pkgname not exist" && exit 1)
}

INDEX_DIR="/var/lib/scratchpkg/index"
CONF_FILE="/etc/scratchpkg.conf"

if [ ! "$1" ]; then
	echo "Please specify package name to list its dependencies"
	exit 1
fi

source "$CONF_FILE"
source "/usr/share/scratchpkg/color"
pkgname=$1

checkpkg			# check for existence port
calcdep $pkgname	# calculate dependencies
loop				# loop through all dependencies

# filter all same dependencies and sort backwards
for i in $(echo $deps | tr ' ' '\n'); do
	[ $(echo $filterdep | tr ' ' '\n' | grep -x $i) ] || filterdep="$filterdep $i"
done

filterdep="$filterdep $pkgname" # add package to install to final dependency list

for alldep in $(echo $filterdep | tr ' ' '\n'); do
	if [ -d $INDEX_DIR/$alldep ]; then
		echo -e "$alldep ${color_green}[installed]${color_reset}"
	else
		echo "$alldep"
	fi
done

exit 0
