#!/bin/bash

RED='\e[0;31m'      #Red
GREEN='\e[0;32m'    #Green
CRESET='\e[0m'		#Reset color

msg() {
	echo -e "${GREEN}==>${CRESET} $1"
}

msgerr() {
	echo -e "${RED}==> ERROR:${CRESET} $1"
}
	
if [ "$UID" != "0" ]; then
	msgerr "Chroot need root access!"
	exit 1
fi

LFS=$1

if [ -z $1 ]; then
	msgerr "Please set directory for chroot!"
	exit 1
fi

if [ ! -d $LFS ]; then
	msgerr "Directory '$LFS' not exist"
	exit 1
fi

pushd $LFS

mount -v --bind /dev $LFS/dev
mount -vt devpts devpts $LFS/dev/pts -o gid=5,mode=620
mount -vt proc proc $LFS/proc
mount -vt sysfs sysfs $LFS/sys
mount -vt tmpfs tmpfs $LFS/run

if [ -h $LFS/dev/shm ]; then
  mkdir -pv $LFS/$(readlink $LFS/dev/shm)
fi

chroot "$LFS" /usr/bin/env -i \
HOME=/root \
TERM="$TERM" \
PS1='\u:\w\$ ' \
PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/bash --login

popd
msg "Chroot exited"

msg "Unmounting virtual filesystem"
umount -v $LFS/dev/pts
umount -v $LFS/dev
umount -v $LFS/run
umount -v $LFS/proc
umount -v $LFS/sys

exit $?
