#!/bin/bash

source "/usr/share/scratchpkg/functions"

if [ ! "$1" ]; then
	msgerr "Please specify package name to list its dependencies order."
	exit 1
fi

while read repodir repourl junk; do
	case $repodir in
		""|"#"*) continue ;;
	esac
	PORT_REPO+=($repodir)
done < /etc/scratchpkg.repo

checkdep() {
	
	if getportpath "$1" >/dev/null; then
		pushd $(getportpath "$1")
			getpkginfo
		popd
	fi
	
	for dep in ${depends[@]}; do
		echo $dep
	done
	
	for mdep in ${makedepends[@]}; do
		echo $mdep
	done
	
}

getportpath() {
	
	for repo in ${PORT_REPO[@]}; do
		if [[ -f $repo/$1/$BUILD_SCRIPT ]]; then
			echo "$(dirname $repo/$1/$BUILD_SCRIPT)"
			return 0
		fi
	done
	return 1
	
}

calc_dep() {
	
	# check currently process package for loop
	if [ ${#CHECK[@]} -gt 0 ]; then
		if [[ "$(echo ${CHECK[@]} | tr " " "\n" | grep -x $1)" == "$1" ]]; then
			msgerr "loop dependency found: $1"
			exit 1
		fi
	fi
	
	# add package to currently process
	CHECK+=($1)
	
	# check dependencies
	for i in $(checkdep "$1"); do
		if [[ $(echo ${DEP[@]} | tr " " "\n" | grep -x $i) = "" ]]; then
			calc_dep $i
		fi
	done
	
	# add dependency to list checked dep
	DEP+=($1)
	
	# delete process package array
	for i in "${!CHECK[@]}"; do
		if [[ ${CHECK[i]} = "$1" ]]; then
			unset 'CHECK[i]'
		fi
	done
	
}

CHECK=()
DEP=()

calc_dep $1

for deps in ${DEP[@]}; do
	if [ -e $INDEX_DIR/$deps/.pkginfo ]; then
		msginst "$deps"
	elif ! getportpath "$deps" >/dev/null; then
		msgmiss "$deps"
	else
		msgnoinst "$deps"
	fi
done

exit 0
