#!/bin/bash
#
#  scratchpkg
#
#  Copyright (c) 2018 by Emmett1  (emmett1.2miligrams@gmail.com)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

if [ "$UID" != 0 ]; then
	echo "This operation need root access. Exiting..."
	exit 1
fi

spkgnew=$(find /etc -regextype posix-extended -regex ".+\.spkgnew" 2> /dev/null)

if [ -z "$spkgnew" ]; then
	echo "Nothing to do. Exiting..."
	exit 0
fi

for file in $spkgnew; do
	clear
	currentfile=${file%.*}
	if [ ! -e "$currentfile" ]; then
		echo "Remove '$file', '$currentfile' not exist."
		rm -f "$file"
		sleep 1
		continue
	fi
	diff -u $currentfile $file --color=always
	if [ $? = 0 ]; then
		echo "Remove '$file', no diff found."
		rm -f "$file"
		sleep 1
		continue
	fi
	echo
	echo "Choose action:"
	echo "1) Keep original"
	echo "2) Replace original with new"
	echo "*) Do nothing"
	echo
	echo -n "Action: "
	read ACTION
	if [ "$ACTION" = "1" ]; then
		echo "Remove '$file'"
		rm -f "$file"
	elif [ "$ACTION" = "2" ]; then
		echo "Replace '$currentfile' with '$file'."
		mv "$file" "$currentfile"
	else
		echo "Doing nothing."
	fi
	sleep 1
done

clear

echo "Done updating package's configuration files."

exit 0
